const productData = [
  {
    name: "Demian",
    image: "https://m.media-amazon.com/images/I/71E4SkSJiKL._SY466_.jpg",
    oPrice: 199,
    author: "Mark Twain",
    year: "10 April 2020",
    discount: "10",
    rating: "4.6",
    price: 180,
    catagory: "thriller",
    desc: `"Demian" by Hermann Hesse is a captivating novel that explores the journey of self-discovery and spiritual awakening of its protagonist,`,
  },
  {
    image: "https://m.media-amazon.com/images/I/61sqBwkMb3L._SY466_.jpg",
    oPrice: 299,
    author: "Hermann Hesse",
    year: "june 2011",
    desc: `Hesse's best-known and most autobiographical work is one of literature's most beautiful evocations of the soul's path to liberation,`,
    discount: "10",
    catagory: "thriller",
    name: "Steppenwolf",
    rating: "4.6",
    price: 213,
  },
  {
    image: "https://m.media-amazon.com/images/I/71udHZOnOML._SY466_.jpg",
    oPrice: 399,
    author: "Mark Twain",
    year: "1 July 2015",
    desc: `Huck is back.. Taken for a son by Widow Douglas; struggling against the society and its attempts to ‘civilize’ him.Escaping his alcoholic father by faking his death, we join him as he voyages down the Mississippi River seeking liberation.`,
    discount: "10",
    name: "The Adventures of Huckleberry Finn",
    catagory: "adventures",
    rating: "4.6",
    price: 399,
  },
  {
    image: "https://m.media-amazon.com/images/I/71hwuNdwQpL._SY466_.jpg",
    oPrice: 199,
    author: "james gosling",
    year: " 11 July 2018",
    desc: `First published in 1919, it is a brilliant journey of the psyche written by one of Germany's most influential writers and thinkers?Herman Hesse. A young man awakens to selfhood and to a world of possibilities beyond the conventions of his upbringing.`,
    discount: "10",
    name: "Demian (General Press) ",
    catagory: "thriller",
    rating: "4.6",
    price: 189,
  },
  {
    image: "https://m.media-amazon.com/images/I/81Y-PQhFjuL._SY466_.jpg",
    oPrice: 199,
    author: "Albert Einstein",
    year: "Paperback – 18 July 2024",
    desc: `Are you ready to delve into one of the most groundbreaking scientific treatises of all time? Albert Einstein's Relativity offers an unparalleled exploration of the principles that have revolutionized our understanding of the universe.`,
    discount: "10",
    name: "Concepts of Physics, Relativity, General Relativity & Quantum Mechanics",
    rating: "4.6",
    catagory: "science fiction",
    price: 166,
  },
  {
    image: "https://m.media-amazon.com/images/I/61yyRK2t2aL._SY466_.jpg",
    year: "Paperback – 21 December 2023",
    oPrice: 199,
    author: "Max Planck and Niels Bohr ",
    name: "Quantum Theory ",
    desc: `Unravel the fabric of reality as these visionary physicists revolutionize our understanding of the subatomic realm. Planck's groundbreaking concept of quantized energy and Bohr's daring atomic model challenge classical notions, `,
    discount: "10",
    rating: "4.6",
    price: 149,
    catagory: "science fiction",
  },
  {
    image: "https://m.media-amazon.com/images/I/710K9pWWZ+L._SY466_.jpg",
    oPrice: 199,
    author: "by Robert Louis Stevenson",
    year: "Paperback – 1 January 2013",
    desc: `Embark on a thrilling adventure with Robert Louis Stevenson's "Treasure Island." Join young Jim Hawkins as he sets sail on a quest for buried treasure, encountering dangerous pirates and facing the ultimate test of bravery. A classic tale of excitement and intrigue.`,
    discount: "10",
    name: "Treasure Island",
    rating: "4.6",
    price: 129,
    catagory: "fantasy",
  },
  {
    image: "https://m.media-amazon.com/images/I/81fedjK1SML._SY466_.jpg",
    oPrice: 199,
    author: "Robert Louis Stevenson",
    year: "Paperback – 20 May 2023",
    desc: `David, the rightful successor to his family's wealth, is abducted as a result of a betrayal, and what begins is an adventure that will change his life forever! Amidst shipwrecks and dangerous events, David discovers his own bravery and what it truly means to be good!`,
    discount: "10",
    name: "Kidnapped by Robert Louis Stevenson",
    rating: "4.6",
    price: 149,
    catagory: "fantasy",
  },
];
const productData2 = [
  {
    image: "https://m.media-amazon.com/images/I/81keZ6LpNWL._SY466_.jpg",
    oPrice: 199,
    author: "Freida McFadden",
    year: "Paperback – 1 January 2022",
    desc: `Working here is my last chance to start fresh. I can pretend to be whoever I like.
Every day I clean the Winchesters' beautiful house top to bottom. `,
    discount: "10",
    name: "The Housemaid",
    rating: "4.6",
    price: 149,
    catagory: "mystery",
  },
  {
    image: "https://m.media-amazon.com/images/I/81+ceFx9BcL._SY466_.jpg",
    oPrice: 299,
    author: "Freida McFadden ",
    year: "Paperback – 30 January 2024",
    desc: `Newlyweds Tricia and Ethan are searching for the house of their dreams. They think they’ve found it in the remote manor that once belonged to Dr. Adrienne Hale, a renowned psychiatrist who years ago vanished without a trace.`,
    discount: "10",
    name: "Never Lie ",
    rating: "4.6",
    price: 199,
    catagory: "mystery",
  },
  {
    image: "https://m.media-amazon.com/images/I/61KGcagQMwL._SY466_.jpg",
    oPrice: 199,
    author: "  H.G. Wells",
    year: " Paperback – 1 February 2017",
    desc: `Here are the biggest enterprise technology acquisitions of 2021 so far, in reverse chronological order.biggest enterprise technology acquisitions of 2021 so far, in reverse chronologicalrse ch`,
    discount: "10",
    name: "The Invisible Man",
    rating: "4.6",
    price: 189,
    catagory: "mystery",
  },
  {
    image: "https://m.media-amazon.com/images/I/91+CQNeCtwL._SY466_.jpg",
    oPrice: 219,
    author: "Nikesh Murali",
    year: "Paperback – 15 July 2023",
    desc: `Prepare to immerse yourself into the heart of darkness as Nikesh Murali, Commonwealth Short Story Prize-winning author and creator of India’s most critically acclaimed horror podcast Indian Noir weaves an unforgettable tapestry of bone-chilling scares and unrelenting terror. `,
    discount: "10",
    name: "Tales of Horror",
    rating: "4.6",
    catagory: "horror",
    price: 199,
  },
  {
    image: "https://m.media-amazon.com/images/I/713-hV5Oz8L._SL1000_.jpg",
    oPrice: 129,
    author: "Oscar Wilde",
    year: " Paperback – 1 February 2021",
    desc: `The Canterville Ghost is a classic tale by Oscar Wilde, first published in 1887. A delightful read for all ages, the story follows the Otis family as they move into Canterville Chase,`,
    discount: "10",
    name: "The Canterville Ghost",
    rating: "4.6",
    catagory: "horror",
    price: 119,
  },

  {
    image: "https://m.media-amazon.com/images/I/71dNsRuYL7L._SY466_.jpg",
    oPrice: 199,
    author: "  STUTI CHANGLE ",
    year: "  Paperback – Notebook, 1 January 2020",
    desc: `What if you ran away from your life today?Twenty years later, three people are looking for you.
One is dying to meet you again.
The other wishes you had never met them.
The third wishes they could have met you at least once.
`,
    discount: "10",
    name: " YOU ONLY LIVE ONCE",
    rating: "4.6",
    catagory: "romance",
    price: 189,
  },
  {
    catagory: "romance",
    image: "https://m.media-amazon.com/images/I/91PQFpYWLwL._SY466_.jpg",
    oPrice: 129,
    author: "Shravya Bhinder",
    year: "  Paperback – 1 January 2019",
    desc: `When in love, you tend to take each other for granted, and sometimes, that can cost you a lifetime of togetherness . . .
Ronnie knew that his first crush was way out of his league, and yet he pursued and wooed Adira. Shyly and from a distance in the beginning, `,
    discount: "10",
    name: "Something I Never Told You",
    rating: "4.6",
    price: 99,
  },
  {
    image: "https://m.media-amazon.com/images/I/71eoNZ1IQYL._SY466_.jpg",
    oPrice: 199,
    author: "Aditya Nighhot",
    year: "Paperback – 10 April 2023",
    desc: `Tagged for Life is the love story of Karan Malhotra, a famous filmmaker’s son, and Ahana Mukherjee, a middle-class girl from Kolkata. Karan and Ahana meet at a college where they have come to pursue a course in film-making. Ahana is an aspiring author but has found no success so far. `,
    discount: "10",
    name: " Will You Be My Wife? ",
    rating: "4.6",
    catagory: "romance",
    price: 179,
  },
];

export { productData, productData2 };
